version: '3'

services:
    api:
        build: './api'
        ports:
            - '3001:3001'

    frontend:
        build: './frontend'
        depends_on:
            - 'api'
        ports:
            - '3000:3000'
